# -*- coding: utf-8 -*-
"""Insurance policy ANN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YntoRmAnrgLe_8bJQup71RmdO015bhzk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_excel('/content/insurance_policies_data.xlsx')

df.sample(5)

df.duplicated().sum()

# Target & Features
TARGET = "Claim Freq"
X = df.drop(columns=[TARGET, "ID", "BirthDate"])
y = df[TARGET]

# Encode target
le = LabelEncoder()
y = le.fit_transform(y.astype(str))

# ---- Handle Features ----
numeric_cols = X.select_dtypes(include=["int64","float64"]).columns.tolist()
cat_cols = X.select_dtypes(include=["object"]).columns.tolist()

# Make sure 'Age' is included in numeric columns if it exists
if 'Age' in X.columns and 'Age' not in numeric_cols:
    numeric_cols.append('Age')

# Remove 'Age' from categorical columns if it's mistakenly there
if 'Age' in cat_cols:
    cat_cols.remove('Age')

# Fill missing
X[numeric_cols] = X[numeric_cols].fillna(X[numeric_cols].median())
X[cat_cols] = X[cat_cols].fillna("Missing")

# Convert BirthDate to Age
df["Age"] = (pd.Timestamp.today() - pd.to_datetime(df["BirthDate"])).dt.days // 365

# Drop unnecessary columns
X = df.drop(columns=[TARGET, "ID", "BirthDate"])

# Preprocessing
numeric_transformer = Pipeline(steps=[
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, numeric_cols),
    ("cat", categorical_transformer, cat_cols)
])

# Convert categorical columns to string type
for col in cat_cols:
    X[col] = X[col].astype(str)

X_pre = preprocessor.fit_transform(X)

# ---- Train/Test Split ----
X_train, X_test, y_train, y_test = train_test_split(X_pre, y, test_size=0.2, random_state=42, stratify=y)

# ---- Build ANN ----
num_classes = len(np.unique(y))
model = Sequential([
    Dense(128, activation="relu", input_dim=X_train.shape[1]),
    BatchNormalization(),
    Dropout(0.3),
    Dense(64, activation="relu"),
    Dense(32, activation="relu"),
    Dense(num_classes, activation="softmax")
])

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

# ---- Train ----
es = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)
history = model.fit(X_train, y_train, validation_split=0.2, epochs=8, batch_size=32, callbacks=[es], verbose=2)

# ---- Evaluate ----
y_pred = np.argmax(model.predict(X_test), axis=1)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# ---- Plot ----
plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Val Loss")
plt.legend()
plt.show()